### ISSUE TITLE
Erro ao atualizar/salvar entidades

### ISSUE THREAD

**Issue by arakenlotufo** [arakenlotufo/mapasculturaisThemeMatoGrosso#1]
Erro ao tentar salvar as entidades Espacos, agentes

**Comment by arakenlotufo** [comment]
![captura de tela em 2017-07-14 14-00-52](https://user-images.githubusercontent.com/12297759/28224399-e6643320-689c-11e7-8ae8-8a9fa85a5051.png)

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
