### ISSUE TITLE
Erro de redirecionamento do login cidadão para o Mapas após realizar o login

### ISSUE THREAD

**Issue by arakenlotufo** [arakenlotufo/mapasculturaisThemeMatoGrosso#3]
Erro de redirecionamento do login cidadão para o Mapas após realizar o login ao   cadastrar novo usuario ou logar

**Comment by arakenlotufo** [comment]
![captura de tela em 2017-07-14 13-45-58](https://user-images.githubusercontent.com/12297759/28223898-239ec496-689b-11e7-9189-66fd10e62e8a.png)

**Comment by thaisrigolon** [comment]
O erro ocorre com o usuário admin (arakenlotufo@secel.mt.gov.br).
Com um usuário padrão cadastrado agora (thais@lfdb.com.br) não acontece o erro.

**Comment by thaisrigolon** [comment]
Ok, issue homologada.
